runtime: python312
env: flex

entrypoint: streamlit run src/sarah_streamlit/testing_app.py --browser.serverAddress 0.0.0.0 --server.port 8080

env_variables:
  PYTHONPATH: /app/src
  BUCKET_NAME: "sarah-testing-db"

instance_class: F2  # Adjust based on your needs

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20 